/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Class.Usuario;
import Conexion.PHPClass;
import com.sun.awt.AWTUtilities;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(this);
        AWTUtilities.setWindowOpaque(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jRadioButtonEstudiante = new javax.swing.JRadioButton();
        jRadioButtonTutor = new javax.swing.JRadioButton();
        jButtonEntrar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 130, -1));

        jTextFieldCedula.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        getContentPane().add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));

        jTextFieldCorreo.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, -1));

        jTextFieldCiudad.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        getContentPane().add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, -1));

        jTextFieldContraseña.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        getContentPane().add(jTextFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, -1));

        jLabelNombre.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 136, 154));
        jLabelNombre.setText("Nombres:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabelCedula.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(0, 136, 154));
        jLabelCedula.setText("Cedula:");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabelCorreo.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(0, 136, 154));
        jLabelCorreo.setText("Correo:");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabelCiudad.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jLabelCiudad.setForeground(new java.awt.Color(0, 136, 154));
        jLabelCiudad.setText("Ciudad:");
        getContentPane().add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 136, 154));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabelTipoUsuario.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jLabelTipoUsuario.setForeground(new java.awt.Color(0, 136, 154));
        jLabelTipoUsuario.setText("Tipo de usuario:");
        getContentPane().add(jLabelTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jRadioButtonEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonEstudiante);
        jRadioButtonEstudiante.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jRadioButtonEstudiante.setForeground(new java.awt.Color(0, 136, 154));
        jRadioButtonEstudiante.setText("Estudiante");
        getContentPane().add(jRadioButtonEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jRadioButtonTutor.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonTutor);
        jRadioButtonTutor.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jRadioButtonTutor.setForeground(new java.awt.Color(0, 136, 154));
        jRadioButtonTutor.setText("Tutor");
        getContentPane().add(jRadioButtonTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jButtonEntrar.setBackground(new java.awt.Color(0, 116, 167));
        jButtonEntrar.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Enviar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 116, 167));
        jButtonVolver.setFont(new java.awt.Font("Oswald", 0, 11)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Register.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
       String r = "";
        if (jRadioButtonEstudiante.isSelected())
             r = "E";
        if (jRadioButtonTutor.isSelected())
             r = "T";
        
        new PHPClass().saveInfo(new Usuario(
                Integer.parseInt(jTextFieldCedula.getText()),
                jTextFieldNombre.getText(),
                jTextFieldCiudad.getText(),
                jTextFieldCorreo.getText(),
                jTextFieldContraseña.getText(),
                r));
        
        jTextFieldCedula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCiudad.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldContraseña.setText("");
        buttonGroup1.clearSelection();
        
        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente.");
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        Register.this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JRadioButton jRadioButtonEstudiante;
    private javax.swing.JRadioButton jRadioButtonTutor;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
